/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HoteRouteImport } from './routes/hote'
import { Route as MesDemandesRouteImport } from './routes/mes-demandes'
import { Route as PasseportRouteImport } from './routes/passeport'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as HebergementIdRouteImport } from './routes/hebergement.$id'
import { Route as AuthenticatedMesAnnoncesIndexRouteImport } from './routes/_authenticated/mes-annonces.index'
import { Route as AuthenticatedMesAnnoncesNouvelleRouteImport } from './routes/_authenticated/mes-annonces.nouvelle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HoteRoute = HoteRouteImport.update({
  id: '/hote',
  path: '/hote',
  getParentRoute: () => rootRouteImport,
} as any)
const MesDemandesRoute = MesDemandesRouteImport.update({
  id: '/mes-demandes',
  path: '/mes-demandes',
  getParentRoute: () => rootRouteImport,
} as any)
const PasseportRoute = PasseportRouteImport.update({
  id: '/passeport',
  path: '/passeport',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const HebergementIdRoute = HebergementIdRouteImport.update({
  id: '/hebergement/$id',
  path: '/hebergement/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMesAnnoncesIndexRoute =
  AuthenticatedMesAnnoncesIndexRouteImport.update({
    id: '/mes-annonces/',
    path: '/mes-annonces/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMesAnnoncesNouvelleRoute =
  AuthenticatedMesAnnoncesNouvelleRouteImport.update({
    id: '/mes-annonces/nouvelle',
    path: '/mes-annonces/nouvelle',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hote': typeof HoteRoute
  '/mes-demandes': typeof MesDemandesRoute
  '/passeport': typeof PasseportRoute
  '/recherche': typeof RechercheRoute
  '/hebergement/$id': typeof HebergementIdRoute
  '/mes-annonces/nouvelle': typeof AuthenticatedMesAnnoncesNouvelleRoute
  '/mes-annonces/': typeof AuthenticatedMesAnnoncesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hote': typeof HoteRoute
  '/mes-demandes': typeof MesDemandesRoute
  '/passeport': typeof PasseportRoute
  '/recherche': typeof RechercheRoute
  '/hebergement/$id': typeof HebergementIdRoute
  '/mes-annonces/nouvelle': typeof AuthenticatedMesAnnoncesNouvelleRoute
  '/mes-annonces': typeof AuthenticatedMesAnnoncesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/hote': typeof HoteRoute
  '/mes-demandes': typeof MesDemandesRoute
  '/passeport': typeof PasseportRoute
  '/recherche': typeof RechercheRoute
  '/hebergement/$id': typeof HebergementIdRoute
  '/_authenticated/mes-annonces/nouvelle': typeof AuthenticatedMesAnnoncesNouvelleRoute
  '/_authenticated/mes-annonces/': typeof AuthenticatedMesAnnoncesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/hote'
    | '/mes-demandes'
    | '/passeport'
    | '/recherche'
    | '/hebergement/$id'
    | '/mes-annonces/nouvelle'
    | '/mes-annonces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/hote'
    | '/mes-demandes'
    | '/passeport'
    | '/recherche'
    | '/hebergement/$id'
    | '/mes-annonces/nouvelle'
    | '/mes-annonces'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/hote'
    | '/mes-demandes'
    | '/passeport'
    | '/recherche'
    | '/hebergement/$id'
    | '/_authenticated/mes-annonces/nouvelle'
    | '/_authenticated/mes-annonces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HoteRoute: typeof HoteRoute
  MesDemandesRoute: typeof MesDemandesRoute
  PasseportRoute: typeof PasseportRoute
  RechercheRoute: typeof RechercheRoute
  HebergementIdRoute: typeof HebergementIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hote': {
      id: '/hote'
      path: '/hote'
      fullPath: '/hote'
      preLoaderRoute: typeof HoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-demandes': {
      id: '/mes-demandes'
      path: '/mes-demandes'
      fullPath: '/mes-demandes'
      preLoaderRoute: typeof MesDemandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passeport': {
      id: '/passeport'
      path: '/passeport'
      fullPath: '/passeport'
      preLoaderRoute: typeof PasseportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hebergement/$id': {
      id: '/hebergement/$id'
      path: '/hebergement/$id'
      fullPath: '/hebergement/$id'
      preLoaderRoute: typeof HebergementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mes-annonces/': {
      id: '/_authenticated/mes-annonces/'
      path: '/mes-annonces'
      fullPath: '/mes-annonces/'
      preLoaderRoute: typeof AuthenticatedMesAnnoncesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes-annonces/nouvelle': {
      id: '/_authenticated/mes-annonces/nouvelle'
      path: '/mes-annonces/nouvelle'
      fullPath: '/mes-annonces/nouvelle'
      preLoaderRoute: typeof AuthenticatedMesAnnoncesNouvelleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMesAnnoncesNouvelleRoute: typeof AuthenticatedMesAnnoncesNouvelleRoute
  AuthenticatedMesAnnoncesIndexRoute: typeof AuthenticatedMesAnnoncesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMesAnnoncesNouvelleRoute: AuthenticatedMesAnnoncesNouvelleRoute,
  AuthenticatedMesAnnoncesIndexRoute: AuthenticatedMesAnnoncesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HoteRoute: HoteRoute,
  MesDemandesRoute: MesDemandesRoute,
  PasseportRoute: PasseportRoute,
  RechercheRoute: RechercheRoute,
  HebergementIdRoute: HebergementIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
